port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090

# 海外优化的 DNS 设置
dns:
  enable: true
  listen: 0.0.0.0:53
  # 海外主 DNS（延迟低，速度快）
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - tls://dns.google
    - https://dns.quad9.net/dns-query
    - 208.67.222.222
    - 208.67.220.220
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
